title: This is a Page Name
description: This is a Tagline
google_analytics:
show_downloads: true
# theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - assets/css/prism.css
  - assets/js/prism.js
